<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <StartupObject>OrderValidation.After.Demo.RunScenarios</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderValidation.csproj" />
  </ItemGroup>

</Project>
